# Generated by Django 5.2.16 on 2026-09-04 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userpatientaccess_status_alter_patient_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='insurance_provider',
            field=models.CharField(choices=[('none', 'فاقد بیمه پایه'), ('tamin', 'تأمین اجتماعی'), ('salamat', 'بیمه سلامت ایرانیان'), ('mosahlar', 'خدمات درمانی نیروهای مسلح'), ('other', 'سایر')], default='none', max_length=30),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('standard', 'بیمار / کاربر عادی'), ('doctor', 'پزشک'), ('staff', 'کادر درمان / پرستار')], default='standard', max_length=20)),
                ('medical_id', models.CharField(blank=True, default='', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
