# Generated by Django 5.2.16 on 2026-09-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_patient_insurance_provider_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس'),
        ),
    ]
