# Generated by Django 5.2.16 on 2026-09-06 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_patient_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('medications', models.JSONField(blank=True, default=list)),
                ('care_plans', models.JSONField(blank=True, default=list)),
                ('immunizations', models.JSONField(blank=True, default=list)),
                ('screenings', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_summary', to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TestReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('frequency', models.CharField(choices=[('once', 'یک\u200cبار'), ('monthly', 'ماهانه'), ('every_3_months', 'هر ۳ ماه'), ('every_6_months', 'هر ۶ ماه'), ('yearly', 'سالانه')], default='once', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.patient')),
            ],
        ),
    ]
