# Generated by Django 5.2.16 on 2026-09-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='has_seen_tour',
            field=models.BooleanField(default=False),
        ),
    ]
